### ISSUE TITLE
Travis CI fails repeatedly

### ISSUE THREAD

**Issue by blabber** [raumzeitlabor/rzl-homepage#155]
The last few builds failed. After multiple retries the build succeeds without any reason.

    [...]
    ✔ pre-build test passed successfully!
    npm ERR! EEXIST, open '/home/travis/.npm/33200a30-vis-npm-lodash-2-4-2-package-tgz.lock'
    File exists: /home/travis/.npm/33200a30-vis-npm-lodash-2-4-2-package-tgz.lock
    Move it away, and try again. 

    npm ERR! System Linux 2.6.32-042stab090.5
    npm ERR! command "/home/travis/.nvm/v0.10.38/bin/node" "/home/travis/.nvm/v0.10.38/bin/npm" "install"
    npm ERR! cwd /home/travis/build/raumzeitlabor/rzl-homepage
    npm ERR! node -v v0.10.38
    npm ERR! npm -v 1.4.28
    npm ERR! path /home/travis/.npm/33200a30-vis-npm-lodash-2-4-2-package-tgz.lock
    npm ERR! code EEXIST
    npm ERR! errno 47
    npm ERR! not ok code 0
    The command "npm install" failed and exited with 47 during .

    Your build has been stopped.

**Comment by abrock** [comment]
The build process randomly failed for more than half of my pull requests

**Comment by blabber** [comment]
I closed this issue by accident. This issue is still relevant to me too.

**Comment by abrock** [comment]
BTW, this is by no means a new problem, see #124

**Comment by else** [comment]
I have seen this problem happen several times, and there are also other repositories where this is the case (not rzl-related). 

I'm not quite sure whether this is related to the Travis image or npm. Since the build does not make use of caching, I think it's not our fault. 

As a workaround, restarting the build several times seems to help. But it's a PITA.

I think there is a new Travis image available, so maybe let's give that a try.

**Comment by else** [comment]
Another idea may be updating the dependent package of that library.

**Comment by else** [comment]
Let's see if 8e505f3bbb501d2ebb7a71b82a04340609265efe helps.
